In [1]:
import pandas as pd

In [6]:
# Lê 3 resultados 
dfs = [
pd.read_csv("../experiments_results/raw/raw_birds_results.csv"),
pd.read_csv("../experiments_results/raw/raw_medical_results.csv"),
pd.read_csv("../experiments_results/raw/raw_scene_results.csv")
]

# Ordena por maior R2 para F1 (Quão bem o modelo explica a coluna F1)
dfs = [df.sort_values(by="R2 para F1 (macro averaged by label)", ascending=False) for df in dfs]
for df in dfs:
    display(df.head(5))

,Model,Best_Params,R2 para F1 (macro averaged by label),R2 para Model Size Log,RMSE para F1 (macro averaged by label),RMSE para Model Size Log
7,xgboost_regressor_chain,"{'n_estimators': 869, 'learning_rate': 0.07474...",0.9546,0.9972,0.0315,0.1135
4,xgboost_multi_output,"{'n_estimators': 919, 'learning_rate': 0.06427...",0.9546,0.9977,0.0315,0.1027
6,lgbm_regressor_chain,"{'n_estimators': 994, 'learning_rate': 0.09775...",0.9506,0.9974,0.0329,0.1100
3,catboost_multi_output,"{'iterations': 913, 'learning_rate': 0.0987104...",0.9444,0.9973,0.0349,0.1120
2,lgbm_multi_output,"{'n_estimators': 788, 'learning_rate': 0.05546...",0.9439,0.9972,0.0351,0.1138

,Model,Best_Params,R2 para F1 (macro averaged by label),R2 para Model Size Log,RMSE para F1 (macro averaged by label),RMSE para Model Size Log
7,xgboost_regressor_chain,"{'n_estimators': 996, 'learning_rate': 0.07588...",0.9755,0.9948,0.0340,0.1507
4,xgboost_multi_output,"{'n_estimators': 756, 'learning_rate': 0.09985...",0.9748,0.9949,0.0345,0.1498
2,lgbm_multi_output,"{'n_estimators': 809, 'learning_rate': 0.09933...",0.9731,0.9936,0.0356,0.1671
6,lgbm_regressor_chain,"{'n_estimators': 852, 'learning_rate': 0.09737...",0.9714,0.9935,0.0367,0.1683
3,catboost_multi_output,"{'iterations': 950, 'learning_rate': 0.0608746...",0.9712,0.9951,0.0368,0.1461

,Model,Best_Params,R2 para F1 (macro averaged by label),R2 para Model Size Log,RMSE para F1 (macro averaged by label),RMSE para Model Size Log
4,xgboost_multi_output,"{'n_estimators': 880, 'learning_rate': 0.07746...",0.9627,0.9960,0.0277,0.1441
7,xgboost_regressor_chain,"{'n_estimators': 757, 'learning_rate': 0.06850...",0.9608,0.9948,0.0284,0.1630
3,catboost_multi_output,"{'iterations': 758, 'learning_rate': 0.0996590...",0.9600,0.9961,0.0287,0.1421
6,lgbm_regressor_chain,"{'n_estimators': 998, 'learning_rate': 0.09919...",0.9578,0.9951,0.0295,0.1583
2,lgbm_multi_output,"{'n_estimators': 630, 'learning_rate': 0.08149...",0.9536,0.9957,0.0309,0.1492

#### Aparentemente os melhores modelos variam entre xgboost, lightgbm e catboost, alternando a abordagem entre multi_output e regressor_chain. Possíveis explicações:
- Gradient Boosting Decision Trees (GBDT) são significativamente melhores que modelos lineares ou Redes Neurais em dados tabulares;
- O Boosting cria fronteiras de decisão complexas que capturam melhor a relação não-linear;
- O espaço de busca destes modelos é muito rico, então o Optuna consegue encontrar ótimos pontos de regularização (λ,γ) 
- A diferença entre as abordagens "multi_output" e "regressor_chain" é apenas ruído estatístico. Neste caso, critérios como simplicidade, tempo de treinamento, tamanho do modelo e tempo de inferência devem ser levados em conta.

#### Ainda sim, todos estes resultados foram parecidos. Para obter mais informações sobre estes melhores modelos candidatos, vamos calcular o tamanho do modelo e seu tempo de inferência, para então decidirmos quais modelos testar. O script que faz este cálculo está disponível em `src/get_models_performance.py`; basta executar uma única vez e todos os resultados serão processados.