In [4]:
import pandas as pd
path1 = "./ranked_models/ranked_models_birds.csv"
path2 = "./ranked_models/ranked_models_medical.csv"
path3 = "./ranked_models/ranked_models_enron.csv"
path4 = "./ranked_models/ranked_models_scene.csv"
path5 = "./ranked_models/ranked_models_yeast.csv"
path6 = "./ranked_models/all_models.csv"
df = pd.read_csv(path1)
df.head(6)

,Model_Name,R2_F1,R2_ModelSize_Log,RMSE_F1,RMSE_ModelSize_Log,Disk_Size_mb,Inference_time,Dataset_Source,Weighted_Score
0,xgboost_multi_output,0.9546,0.9977,0.0315,0.1027,24.5571,0.002637,birds,0.969685
1,xgboost_regressor_chain,0.9546,0.9972,0.0315,0.1135,33.8950,0.045598,birds,0.969510
2,lgbm_regressor_chain,0.9506,0.9974,0.0329,0.1100,10.5283,0.023401,birds,0.966980
3,catboost_multi_output,0.9444,0.9973,0.0349,0.1120,14.5102,0.003020,birds,0.962915
4,lgbm_multi_output,0.9439,0.9972,0.0351,0.1138,8.0488,0.011798,birds,0.962555
5,mlp_native,0.9180,0.9973,0.0424,0.1104,1.2649,0.000682,birds,0.945755

In [5]:
df2 = pd.read_csv(path2)
df2.head(6)

,Model_Name,R2_F1,R2_ModelSize_Log,RMSE_F1,RMSE_ModelSize_Log,Disk_Size_mb,Inference_time,Dataset_Source,Weighted_Score
0,xgboost_regressor_chain,0.9755,0.9948,0.0340,0.1507,22.4501,0.004476,medical,0.982255
1,xgboost_multi_output,0.9748,0.9949,0.0345,0.1498,16.5610,0.002338,medical,0.981835
2,lgbm_multi_output,0.9731,0.9936,0.0356,0.1671,7.7694,0.002508,medical,0.980275
3,catboost_multi_output,0.9712,0.9951,0.0368,0.1461,29.9580,0.002755,medical,0.979565
4,lgbm_regressor_chain,0.9714,0.9935,0.0367,0.1683,5.9617,0.004151,medical,0.979135
5,mlp_native,0.9429,0.9936,0.0519,0.1668,0.6919,0.000605,medical,0.960645

In [6]:
df3 = pd.read_csv(path3)
df3.head(6)

,Model_Name,R2_F1,R2_ModelSize_Log,RMSE_F1,RMSE_ModelSize_Log,Disk_Size_mb,Inference_time,Dataset_Source,Weighted_Score
0,xgboost_multi_output,0.9672,0.9928,0.0097,0.1891,25.1153,0.002230,enron,0.976160
1,xgboost_regressor_chain,0.9661,0.9917,0.0098,0.2030,16.4276,0.004648,enron,0.975060
2,lgbm_multi_output,0.9641,0.9927,0.0101,0.1905,8.9223,0.002254,enron,0.974110
3,lgbm_regressor_chain,0.9638,0.9916,0.0101,0.2046,10.1653,0.003856,enron,0.973530
4,catboost_multi_output,0.9601,0.9926,0.0107,0.1912,15.1407,0.002762,enron,0.971475
5,random_forest_multi_output,0.9157,0.9798,0.0155,0.3169,8773.0649,0.145105,enron,0.938135

In [7]:
df4 = pd.read_csv(path4)
df4.head(6)

,Model_Name,R2_F1,R2_ModelSize_Log,RMSE_F1,RMSE_ModelSize_Log,Disk_Size_mb,Inference_time,Dataset_Source,Weighted_Score
0,xgboost_multi_output,0.9627,0.9960,0.0277,0.1441,25.1796,0.032402,scene,0.974355
1,xgboost_regressor_chain,0.9608,0.9948,0.0284,0.1630,28.7287,0.098400,scene,0.972700
2,catboost_multi_output,0.9600,0.9961,0.0287,0.1421,23.9003,0.003136,scene,0.972635
3,lgbm_regressor_chain,0.9578,0.9951,0.0295,0.1583,10.9199,0.031786,scene,0.970855
4,lgbm_multi_output,0.9536,0.9957,0.0309,0.1492,6.3988,0.012395,scene,0.968335
5,mlp_native,0.8923,0.9937,0.0470,0.1808,0.9239,0.000501,scene,0.927790

In [8]:
df5 = pd.read_csv(path5)
df5.head(6)

,Model_Name,R2_F1,R2_ModelSize_Log,RMSE_F1,RMSE_ModelSize_Log,Disk_Size_mb,Inference_time,Dataset_Source,Weighted_Score
0,xgboost_regressor_chain,0.9610,0.9967,0.0142,0.1321,31.3966,0.009125,yeast,0.973495
1,xgboost_multi_output,0.9572,0.9971,0.0149,0.1248,17.4837,0.040582,yeast,0.971165
2,catboost_multi_output,0.9569,0.9970,0.0149,0.1259,30.8398,0.010583,yeast,0.970935
3,lgbm_regressor_chain,0.9517,0.9963,0.0158,0.1409,9.1377,0.003928,yeast,0.967310
4,lgbm_multi_output,0.9494,0.9964,0.0162,0.1379,9.0190,0.012198,yeast,0.965850
5,random_forest_multi_output,0.8745,0.9823,0.0255,0.3067,1615.7167,0.027074,yeast,0.912230

In [10]:
df6 = pd.read_csv(path6)
df6

,Dataset_Source,Model_Name,R2_F1,R2_ModelSize_Log,Weighted_Score,Inference_time,Disk_Size_mb,RMSE_F1,RMSE_ModelSize_Log
0,birds,xgboost_multi_output,0.9546,0.9977,0.969685,0.002637,24.5571,0.0315,0.1027
1,birds,xgboost_regressor_chain,0.9546,0.9972,0.969510,0.045598,33.8950,0.0315,0.1135
2,birds,lgbm_regressor_chain,0.9506,0.9974,0.966980,0.023401,10.5283,0.0329,0.1100
3,birds,catboost_multi_output,0.9444,0.9973,0.962915,0.003020,14.5102,0.0349,0.1120
4,birds,lgbm_multi_output,0.9439,0.9972,0.962555,0.011798,8.0488,0.0351,0.1138
5,birds,mlp_native,0.9180,0.9973,0.945755,0.000682,1.2649,0.0424,0.1104
6,birds,random_forest_multi_output,0.9161,0.9880,0.941265,0.019495,3260.4405,0.0429,0.2351
7,birds,random_forest_regressor_chain,0.9164,0.9872,0.941180,0.238372,11954.5458,0.0428,0.2423
8,birds,random_forest_native,0.8644,0.9867,0.907205,0.008707,1113.6949,0.0545,0.2472
9,birds,knn_native,0.8156,0.9641,0.867575,0.012424,133.6284,0.0636,0.4064
10,birds,ridge_multi_output,0.7511,0.9431,0.818300,0.000904,0.0170,0.0738,0.5115
11,enron,xgboost_multi_output,0.9672,0.9928,0.976160,0.002230,25.1153,0.0097,0.1891
12,enron,xgboost_regressor_chain,0.9661,0.9917,0.975060,0.004648,16.4276,0.0098,0.2030
13,enron,lgbm_multi_output,0.9641,0.9927,0.974110,0.002254,8.9223,0.0101,0.1905
14,enron,lgbm_regressor_chain,0.9638,0.9916,0.973530,0.003856,10.1653,0.0101,0.2046
15,enron,catboost_multi_output,0.9601,0.9926,0.971475,0.002762,15.1407,0.0107,0.1912
16,enron,random_forest_multi_output,0.9157,0.9798,0.938135,0.145105,8773.0649,0.0155,0.3169
17,enron,random_forest_regressor_chain,0.9147,0.9783,0.936960,0.065112,5637.1456,0.0156,0.3288
18,enron,random_forest_native,0.8856,0.9798,0.918570,0.047762,4159.6245,0.0180,0.3172
19,enron,mlp_native,0.8551,0.9885,0.901790,0.000565,0.5215,0.0203,0.2388
20,enron,knn_native,0.8670,0.9647,0.901195,0.008741,101.7519,0.0194,0.4190
21,enron,ridge_multi_output,0.7287,0.9386,0.802165,0.001004,0.0170,0.0278,0.5526
22,medical,xgboost_regressor_chain,0.9755,0.9948,0.982255,0.004476,22.4501,0.0340,0.1507
23,medical,xgboost_multi_output,0.9748,0.9949,0.981835,0.002338,16.5610,0.0345,0.1498
24,medical,lgbm_multi_output,0.9731,0.9936,0.980275,0.002508,7.7694,0.0356,0.1671
25,medical,catboost_multi_output,0.9712,0.9951,0.979565,0.002755,29.9580,0.0368,0.1461
26,medical,lgbm_regressor_chain,0.9714,0.9935,0.979135,0.004151,5.9617,0.0367,0.1683
27,medical,mlp_native,0.9429,0.9936,0.960645,0.000605,0.6919,0.0519,0.1668
28,medical,random_forest_multi_output,0.9285,0.9848,0.948205,0.108483,9193.4477,0.0580,0.2577
29,medical,random_forest_regressor_chain,0.9284,0.9841,0.947895,0.149512,5142.7009,0.0581,0.2636
30,medical,random_forest_native,0.8691,0.9842,0.909385,0.035299,4422.7766,0.0786,0.2631
31,medical,knn_native,0.8405,0.9623,0.883130,0.002484,93.9530,0.0867,0.4059
32,medical,ridge_multi_output,0.8072,0.9669,0.863095,0.000971,0.0170,0.0953,0.3806
33,scene,xgboost_multi_output,0.9627,0.9960,0.974355,0.032402,25.1796,0.0277,0.1441
34,scene,xgboost_regressor_chain,0.9608,0.9948,0.972700,0.098400,28.7287,0.0284,0.1630
35,scene,catboost_multi_output,0.9600,0.9961,0.972635,0.003136,23.9003,0.0287,0.1421
36,scene,lgbm_regressor_chain,0.9578,0.9951,0.970855,0.031786,10.9199,0.0295,0.1583
37,scene,lgbm_multi_output,0.9536,0.9957,0.968335,0.012395,6.3988,0.0309,0.1492
38,scene,mlp_native,0.8923,0.9937,0.927790,0.000501,0.9239,0.0470,0.1808
39,scene,random_forest_multi_output,0.8753,0.9845,0.913520,0.169973,6761.4068,0.0506,0.2831
40,scene,random_forest_regressor_chain,0.8754,0.9843,0.913515,0.501751,6630.5735,0.0506,0.2847
41,scene,random_forest_native,0.7895,0.9849,0.857890,0.044718,3333.1774,0.0658,0.2795
42,scene,knn_native,0.7152,0.9623,0.801685,0.013050,98.8052,0.0765,0.4411
43,scene,ridge_multi_output,0.7005,0.9489,0.787440,0.000928,0.0170,0.0784,0.5136
44,yeast,xgboost_regressor_chain,0.9610,0.9967,0.973495,0.009125,31.3966,0.0142,0.1321
45,yeast,xgboost_multi_output,0.9572,0.9971,0.971165,0.040582,17.4837,0.0149,0.1248
46,yeast,catboost_multi_output,0.9569,0.9970,0.970935,0.010583,30.8398,0.0149,0.1259
47,yeast,lgbm_regressor_chain,0.9517,0.9963,0.967310,0.003928,9.1377,0.0158,0.1409
48,yeast,lgbm_multi_output,0.9494,0.9964,0.965850,0.012198,9.0190,0.0162,0.1379
49,yeast,random_forest_multi_output,0.8745,0.9823,0.912230,0.027074,1615.7167,0.0255,0.3067
50,yeast,random_forest_regressor_chain,0.8698,0.9806,0.908580,0.085228,4232.8526,0.0259,0.3213
51,yeast,mlp_native,0.8181,0.9930,0.879315,0.000355,0.5026,0.0307,0.1926
52,yeast,random_forest_native,0.8159,0.9825,0.874210,0.030189,3489.6740,0.0308,0.3047
53,yeast,knn_native,0.7086,0.9522,0.793860,0.017662,120.6090,0.0388,0.5043
54,yeast,ridge_multi_output,0.5616,0.9108,0.683820,0.001005,0.0170,0.0476,0.6888